"use client";

import { FormEvent, useEffect, useState } from "react";

type Metrics = { precision: number | null; recall: number | null; f1: number | null; accuracy: number | null; falsePositiveRate: number | null; falseNegativeRate: number | null; brierScore: number | null; expectedCalibrationError: number | null; falsePositive: number; falseNegative: number };
type Run = { id: string; case_count: number; source_commit: string; scoring_policy: string; created_at: string; metrics: Metrics; calibration: { eligible: boolean; reason: string } | null };
type Policy = { id: string; evaluation_run_id: string; sample_count: number; active: number; activated_at: string | null };

const FAMILIES = ["", "hate_discrimination", "abusive_language", "coded_expression", "violent_threat", "health_claim", "financial_guarantee", "income_claim", "education_outcome", "legal_outcome", "privacy_intrusion", "urgency", "general_substantiation"];
const FAMILY_LABELS: Record<string, string> = { hate_discrimination: "혐오·차별", abusive_language: "욕설·공격", coded_expression: "숨은 은어·코드", violent_threat: "폭력·위협", health_claim: "의료·효능", financial_guarantee: "금융 보장", income_claim: "수익·소득", education_outcome: "교육 성과", legal_outcome: "법률 결과", privacy_intrusion: "개인정보 침해", urgency: "과도한 긴급성", general_substantiation: "일반 과장·입증" };
function percent(value: number | null | undefined) { return value === null || value === undefined ? "측정 불가" : `${(value * 100).toFixed(1)}%`; }

export function EvaluationWorkbench({ csrfToken }: { csrfToken: string }) {
  const [cases, setCases] = useState<Array<Record<string, unknown>>>([]);
  const [runs, setRuns] = useState<Run[]>([]);
  const [policies, setPolicies] = useState<Policy[]>([]);
  const [text, setText] = useState(""); const [expectedRisk, setExpectedRisk] = useState(true); const [expectedFamily, setExpectedFamily] = useState(""); const [context, setContext] = useState("direct");
  const [state, setState] = useState<"idle" | "loading" | "failed">("idle"); const [message, setMessage] = useState("");
  const latest = runs[0];
  async function refresh() { const response = await fetch("/api/manage/evaluation", { credentials: "same-origin", cache: "no-store" }); const payload = await response.json() as { cases?: Array<Record<string, unknown>>; runs?: Run[]; policies?: Policy[]; message?: string }; if (!response.ok) throw new Error(payload.message ?? "평가 데이터를 읽지 못했습니다."); setCases(payload.cases ?? []); setRuns(payload.runs ?? []); setPolicies(payload.policies ?? []); }
  useEffect(() => { const timer = window.setTimeout(() => { refresh().catch(() => undefined); }, 0); return () => window.clearTimeout(timer); }, []);
  async function mutate(body: Record<string, unknown>) { const response = await fetch("/api/manage/evaluation", { method: "POST", credentials: "same-origin", cache: "no-store", headers: { "content-type": "application/json", "x-riskshield-csrf": csrfToken }, body: JSON.stringify(body) }); const payload = await response.json() as { message?: string; caseCount?: number }; if (!response.ok) throw new Error(payload.message ?? "평가 작업을 완료하지 못했습니다."); return payload; }
  async function addCase(event: FormEvent) { event.preventDefault(); setState("loading"); setMessage(""); try { await mutate({ action: "add_case", text, expectedRisk, expectedFamily: expectedFamily || null, context }); setText(""); setState("idle"); setMessage("라벨 사례를 추가했습니다."); await refresh(); } catch (error) { setState("failed"); setMessage(error instanceof Error ? error.message : "사례를 추가하지 못했습니다."); } }
  async function runEvaluation() { setState("loading"); setMessage(""); try { const payload = await mutate({ action: "run" }); setState("idle"); setMessage(`${payload.caseCount ?? 0}개 라벨 사례로 현재 규칙을 평가했습니다.`); await refresh(); } catch (error) { setState("failed"); setMessage(error instanceof Error ? error.message : "평가를 실행하지 못했습니다."); } }
  async function activate(policyId: string) { setState("loading"); setMessage(""); try { const response = await fetch("/api/manage/evaluation/calibration", { method: "POST", credentials: "same-origin", cache: "no-store", headers: { "content-type": "application/json", "x-riskshield-csrf": csrfToken }, body: JSON.stringify({ policyId }) }); const payload = await response.json() as { message?: string }; if (!response.ok) throw new Error(payload.message ?? "보정 정책을 활성화하지 못했습니다."); setState("idle"); setMessage("보정 점수 표시를 활성화했습니다. 위험 판정 임계값은 그대로 유지됩니다."); await refresh(); } catch (error) { setState("failed"); setMessage(error instanceof Error ? error.message : "보정 정책을 활성화하지 못했습니다."); } }
  return <div className="evaluationWorkbench">
    <section className="managementCard evaluationHero"><div><span className="manageHeroEyebrow">LABELED EVALUATION</span><h2>실제 라벨 데이터로 품질 측정</h2><p>사람이 위험·비위험 정답을 붙인 문장을 현재 활성 규칙으로 다시 분석해 정확도와 오탐·미탐을 계산합니다.</p></div><button className="pressable primaryButton" type="button" onClick={runEvaluation} disabled={state === "loading" || !cases.length}>{state === "loading" ? "실행 중…" : `${cases.length}개 사례 평가 실행`}</button></section>
    {latest ? <section className="evaluationMetricGrid" aria-label="최근 평가 지표">{[["정확도", percent(latest.metrics.accuracy)], ["정밀도", percent(latest.metrics.precision)], ["재현율", percent(latest.metrics.recall)], ["F1", percent(latest.metrics.f1)], ["오탐", String(latest.metrics.falsePositive)], ["미탐", String(latest.metrics.falseNegative)], ["Brier", latest.metrics.brierScore?.toFixed(3) ?? "측정 불가"], ["ECE", latest.metrics.expectedCalibrationError?.toFixed(3) ?? "측정 불가"]].map(([label, value]) => <article key={label}><span>{label}</span><strong>{value}</strong></article>)}</section> : <section className="managementCard"><h2>아직 평가 실행이 없습니다.</h2><p>아래에 위험 사례와 정상·비판 문맥 사례를 함께 추가한 뒤 평가를 실행하세요.</p></section>}
    <div className="evaluationLayout"><form className="managementCard evaluationCaseForm" onSubmit={addCase}><span className="manageHeroEyebrow">정답 데이터</span><h2>라벨 사례 추가</h2><p>분석기가 맞혀야 할 문장과 정답을 한 건씩 저장합니다. 위험 사례와 경고·인용 같은 비위험 사례를 함께 넣으세요.</p><label className="formField">평가 문장<textarea rows={6} value={text} onChange={(event) => setText(event.target.value)} required maxLength={2000} placeholder="예: 이 표현은 사용하지 마세요." /></label><div className="evaluationFieldGrid"><label className="formField">정답<select value={expectedRisk ? "risk" : "safe"} onChange={(event) => setExpectedRisk(event.target.value === "risk")}><option value="risk">위험 표현</option><option value="safe">비위험·경고·인용</option></select></label><label className="formField">위험 범주<select value={expectedFamily} onChange={(event) => setExpectedFamily(event.target.value)}>{FAMILIES.map((family) => <option key={family || "none"} value={family}>{family ? FAMILY_LABELS[family] ?? family : "선택 안 함"}</option>)}</select></label><label className="formField">문맥<select value={context} onChange={(event) => setContext(event.target.value)}><option value="direct">직접 사용</option><option value="quotation">인용</option><option value="warning">경고·금지</option><option value="criticism">비판·설명</option></select></label></div><button className="pressable primaryButton" type="submit" disabled={state === "loading" || !text.trim()}>사례 저장</button></form>
    <section className="managementCard"><span className="manageHeroEyebrow">CALIBRATION</span><h2>점수 보정 정책</h2><p>최소 20개, 위험·비위험 각 5개 이상일 때만 단조 보정표를 만듭니다. 보정은 화면의 숫자에만 적용하고 위험 판정 기준은 바꾸지 않습니다.</p><div className="calibrationPolicyList">{policies.length ? policies.map((policy) => <article key={policy.id}><div><strong>{policy.sample_count}개 사례</strong><span>{policy.evaluation_run_id}</span></div>{policy.active ? <span className="statusPill" data-tone="success">사용 중</span> : <button className="pressable secondaryButton" type="button" onClick={() => activate(policy.id)} disabled={state === "loading"}>보정 점수 사용</button>}</article>) : <p>활성화 가능한 보정 정책이 아직 없습니다.</p>}</div></section></div>
    {message ? <p className={state === "failed" ? "configurationNote" : "collectorSuccess"} role={state === "failed" ? "alert" : "status"}>{message}</p> : null}
    <section className="managementCard"><h2>라벨 데이터 현황</h2><div className="evaluationCaseList">{cases.slice(0, 30).map((item) => <article key={String(item.id)}><span className="statusPill" data-tone={item.expected_risk ? "critical" : "success"}>{item.expected_risk ? "위험" : "비위험"}</span><p>{String(item.text)}</p><small>{String(item.expected_family ?? "범주 미지정")} · {String(item.context)}</small></article>)}</div></section>
  </div>;
}
